spring.application.name=coordinator
server.port=8082

observability.otel.collector-grpc-endpoint=http://localhost:4317
observability.otel.connection-timeout-seconds=5
observability.metric.read-interval-seconds=30
observability.metric.export-timeout-seconds=10
observability.log.export-timeout-seconds=10
observability.log.max-batch-size=512
observability.log.max-queue-size=2048

coordinator.producer.policy-api=/api/v1/policies
coordinator.consumer.policy-api=/api/v1/policies
coordinator.producer.base-urls[0]=http://localhost:8080
coordinator.consumer.base-urls[0]=http://localhost:8081
coordinator.broker.bootstrapServers=localhost:9092
coordinator.broker.ids[0]=1