spring:
  application:
    name: coordinator

server:
  port: 8082

observability:
  otel:
    collector-grpc-endpoint: http://localhost:4317
    connection-timeout-seconds: 5
  metric:
    read-interval-seconds: 30
    export-timeout-seconds: 10
  log:
    export-timeout-seconds: 10
    max-batch-size: 512
    max-queue-size: 2048

prometheus:
  url: http://localhost:9090

producer:
  policy-api: /api/v1/policies
  instances:
    - base-url: http://localhost:8080
      prom-label: producer-1

consumer:
  policy-api: /api/v1/policies
  instances:
    - base-url: http://localhost:8081
      prom-label: consumer-1

broker:
  bootstrapServers: localhost:9092
  ids:
    - broker-1

regime-detection:
  metric-detection-map:
    # for consumer
    records-lag-max:
      type: ewma_cusum
      ewma-alpha: 0.2
      cusum-threshold: 2000
      cusum-drift: 50

    fetch-rate:
      type: ewma_cusum
      ewma-alpha: 0.4
      cusum-threshold: 500
      cusum-drift: 20

    commit-rate:
      type: ewma_cusum
      ewma-alpha: 0.5
      cusum-threshold: 300
      cusum-drift: 10

    join-total:
      type: event
      event-threshold: 0

    # for producer
    record-send-rate:
      type: ewma_cusum
      ewma-alpha: 0.3
      cusum-threshold: 5000
      cusum-drift: 100

    outgoing-byte-rate:
      type: ewma_cusum
      ewma-alpha: 0.3
      cusum-threshold: 500000
      cusum-drift: 10000

    record-size-avg:
      type: ewma_cusum
      ewma-alpha: 0.2
      cusum-threshold: 500
      cusum-drift: 10

    request-latency-avg:
      type: ewma_cusum
      ewma-alpha: 0.4
      cusum-threshold: 20
      cusum-drift: 2

    request-latency-max:
      type: ewma_cusum
      ewma-alpha: 0.4
      cusum-threshold: 50
      cusum-drift: 5

    buffer-available-bytes:
      type: ewma_cusum
      ewma-alpha: 0.3
      cusum-threshold: 10000000
      cusum-drift: 1000000

    # for broker
    disk-io:
      type: ewma_cusum
      ewma-alpha: 0.3
      cusum-threshold: 1000
      cusum-drift: 50

    network-io:
      type: ewma_cusum
      ewma-alpha: 0.3
      cusum-threshold: 1000
      cusum-drift: 50

    replica-lag:
      type: ewma_cusum
      ewma-alpha: 0.4
      cusum-threshold: 500
      cusum-drift: 20

    partition-load:
      type: ewma_cusum
      ewma-alpha: 0.4
      cusum-threshold: 500
      cusum-drift: 20

workload-classification:
  metrics:
    # for producer
    record-send-rate:
      streaming:
        operator: ">"
        threshold: 40000
      batch:
        operator: "<="
        threshold: 40000

    outgoing-byte-rate:
      streaming:
        operator: ">"
        threshold: 800000
      batch:
        operator: "<="
        threshold: 800000

    record-size-avg:
      streaming:
        operator: "<"
        threshold: 500
      batch:
        operator: ">="
        threshold: 500

    request-latency-avg:
      streaming:
        operator: "<"
        threshold: 20
      batch:
        operator: ">="
        threshold: 20

    request-latency-max:
      streaming:
        operator: "<"
        threshold: 50
      batch:
        operator: ">="
        threshold: 50

    buffer-available-bytes:
      streaming:
        operator: ">"
        threshold: 20000000
      batch:
        operator: "<="
        threshold: 20000000

    # for consumer
    records-lag-max:
      streaming:
        operator: "<"
        threshold: 1000
      batch:
        operator: ">="
        threshold: 1000

    fetch-rate:
      streaming:
        operator: ">"
        threshold: 1000
      batch:
        operator: "<="
        threshold: 1000

    commit-rate:
      streaming:
        operator: ">"
        threshold: 800
      batch:
        operator: "<="
        threshold: 800

    join-total:
      streaming:
        operator: "=="
        threshold: 0
      batch:
        operator: ">"
        threshold: 0

    # for broker
    disk-io:
      streaming:
        operator: "<"
        threshold: 800
      batch:
        operator: ">="
        threshold: 800

    network-io:
      streaming:
        operator: ">"
        threshold: 800
      batch:
        operator: "<="
        threshold: 800

    replica-lag:
      streaming:
        operator: "<"
        threshold: 500
      batch:
        operator: ">="
        threshold: 500

    partition-load:
      streaming:
        operator: "<"
        threshold: 500
      batch:
        operator: ">="
        threshold: 500

policy-bank:
  workloads:
    streaming:
      producer:
        batch-size: 32768
        linger-ms: 5
        buffer-memory: 67108864
        compression-type: lz4

      consumer:
        fetch-min-bytes: 1
        fetch-max-wait-ms: 50
        max-poll-records: 500

      broker:
        num-partitions: 12
        replication-factor: 2
        log-segment-bytes: 536870912
        min-in-sync-replicas: 1

    batch:
      producer:
        batch-size: 131072
        linger-ms: 50
        buffer-memory: 134217728
        compression-type: zstd

      consumer:
        fetch-min-bytes: 65536
        fetch-max-wait-ms: 500
        max-poll-records: 2000

      broker:
        num-partitions: 6
        replication-factor: 3
        log-segment-bytes: 1073741824
        min-in-sync-replicas: 2
