spring.application.name=producer
server.port=8080

observability.otel.collector-grpc-endpoint=http://localhost:4317
observability.otel.connection-timeout-seconds=5
observability.metric.read-interval-seconds=30
observability.metric.export-timeout-seconds=10
observability.log.export-timeout-seconds=10
observability.log.max-batch-size=512
observability.log.max-queue-size=2048

producer.batch-size=32768
producer.linger-ms=5
producer.buffer-memory=67108864
producer.compression-type=lz4

producer.bootstrap-servers=localhost:9092
producer.topic=messages
producer.id=producer-1