receivers:
  kafka:
    brokers:
      - kafka-logs:19094
    topic: "otel-logs"
    encoding: "otlp_proto"
    group_id: "otel-logs-consumer"
    initial_offset: earliest

processors:
  batch:
    timeout: 10s

exporters:
  elasticsearch:
    endpoints:
      - http://elasticsearch:9200
    logs_index: otel-logs
    sending_queue:
      enabled: true
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [kafka]
      processors: [batch]
      exporters: [elasticsearch]